const en = {
	header: {
		quote:
			'Books are the ships of thoughts, wandering through the waves of time.',
		author: 'Francis Bacon',
		title1: 'Will help you to',
		p1: 'Create your goal faster and proceed to read',
		p2: 'Divide process proportionally for each day',
		p3: 'Track your success',
		title2: 'You may also',
		p4: 'Pose your own independent point of view',
		p5: 'Improve your professional skills according to new knowledge',
		p6: 'Become an interesting interlocutor',
		logout: 'Logout',
	},
	register: {
		login: 'login',
		register: 'register',
		text: 'Are you with us?',
	},
	libraryForm: {
		book: 'Book title',
		author: 'Author',
		date: 'Publication date',
		pages: 'Amount of pages',
		btnAdd: 'Add',
	},
	mobileLibraryItem: {
		author: 'Author',
		year: 'Year',
		pages: 'Pages',
		rating: 'Rating',
		btn: 'Resume',
	},
	readingListHeaders: {
		title: 'Book Title',
		author: 'Author',
		year: 'Year',
		pages: 'Pages',
		rating: 'Rating',
	},
	listHeaders: {
		title: 'Book Title',
		author: 'Author',
		year: 'Year',
		pages: 'Pages',
	},
	libraryListHeaders: {
		going: 'Going to read',
		reading: 'Reading now',
		done: 'Already read',
		other: 'Other',
	},
	libraryEmpty: {
		step1: 'Step 1.',
		text1: 'Create your own library',
		text2: 'Add there books which you are going to read.',
		step2: 'Step 2.',
		text3: 'Create your first training',
		text4: 'Set a goal, choose period, start training.',
		btn: 'Ok',
	},
	timer: {
		title1: 'Years countdown',
		title2: 'Goals countdown',
		days: 'Days',
		hours: 'Hours',
		min: 'Mins',
		sec: 'Seconds',
	},
	team: {
		footerText: '"Books Reading" by',
		teamButton: 'Go back',
	},
};
export default en;
